import type { Metadata } from "next";
// Remove unused Geist imports
import { Space_Grotesk } from "next/font/google"; 
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";

// Use the full object correctly
const grotesk_font = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Correctly apply the generated class name using .className
    <html lang="en">
      <body
        className={`${grotesk_font.className} antialiased`}
      >
<SmoothScroll>
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}